language: node_js
node_js:
  - '9'
sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: osx
      osx_image: "xcode10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
#before_cache:
#  - rm -rf $HOME/.cache/electron-builder/wine
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
notifications:
  email: false
script:
  - yarn install
  - yarn build
  - yarn dist
deploy:
  provider: script
  script:
    - cd dist
    - echo uploading to sftp://${SFTP_HOST}${SFTP_PATH}/${TRAVIS_OS_NAME}
    - curl -k -u ${SFTP_USER}:${SFTP_PASSWORD} -T ./latest.yml --key /tmp/sftp_rsa sftp://${SFTP_HOST}${SFTP_PATH}/${TRAVIS_OS_NAME}
    - echo "Uploaded latest.yml"
    - find ./ -name 'eMusic Setup*.exe' -type f -exec curl -u ${SFTP_USER}:${SFTP_PASSWORD} -T {} sftp://${SFTP_HOST}${SFTP_PATH}/${TRAVIS_OS_NAME} \;
    - echo "Uploaded package"
#  on:
#    tags: true
