language: node_js
node_js:
  - '9'
sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: osx
      osx_image: "xcode10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
#before_cache:
#  - rm -rf $HOME/.cache/electron-builder/wine
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
notifications:
  email: false
script:
  - yarn install
  - yarn build
  - yarn dist
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $PUBLISH_TOKEN
  file_glob: true
  draft: true
  file: dist/*
#  provider: script
#  script: "node scripts/deploy.js"
#  script: "/bin/sh ./travis-deploy.sh"
#  on:
#    tags: true
