language: node_js
node_js:
  - '9'
sudo: required
matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - os: osx
      osx_image: "xcode10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
#before_cache:
#  - rm -rf $HOME/.cache/electron-builder/wine
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install curl && brew link curl --force; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://curl.haxx.se/download/curl-7.61.1.tar.gz && tar -xvf curl-7.61.1.tar.gz && cd curl-7* && ./configure && make &&make install; fi
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
notifications:
  email: false
script:
  - yarn install
  - yarn build
  - yarn dist
deploy:
  skip_cleanup: true
  provider: script
#  script: "node scripts/deploy.js"
  script: "/bin/sh ./travis-deploy.sh"
#  on:
#    tags: true
