# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"
skip_tags: true
environment:
  matrix:
    - nodejs_version: 9
platform:
  - x64
init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn
build_script:
  - yarn build
  - yarn dist
  - for /f %a in ('dir /b /s dist\eMusic*.exe') do xcopy "%a" .\ /i
  - copy dist/latest.yml latest.yml
test: off
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> package.json
  - '%USERPROFILE%\.electron'
artifacts:
  - path: ./eMusic*.exe
    name: Installer
  - path: latest.yml
    name: Latest
